services:
  - type: web
    name: sistema-inventario-backend
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    rootDir: backend
    startCommand: node index.js
    envVars:
      - key: DB_HOST
        value: localhost
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: 
      - key: DB_NAME
        value: inventario_ropa
      - key: PORT
        value: 3001
