services:
  - type: web
    name: backend-inventario
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: node index.js
    envVars:
      - key: DB_HOST
        value: localhost
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: 
      - key: DB_NAME
        value: inventario_ropa
      - key: PORT
        value: 3001
